version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
resolve_s3 = true
stack_name = "PyPlate-macro"
s3_prefix = "PyPlate-macro"
capabilities = "CAPABILITY_IAM"
template = "macro.yaml"

[test]
[test.deploy]
[test.deploy.parameters]
resolve_s3 = true
stack_name = "PyPlate-macro-test"
s3_prefix = "PyPlate-macro-test"
capabilities = "CAPABILITY_IAM"
template = "test.yaml"
